翻譯 第七章 Git 工具
progit/progit2-zh-tw pull request #41
Opened 2020-04-01 14:43 UTC by chenuin

翻譯 [第七章](https://github.com/progit/progit2-zh-tw/blob/master/ch07-git-tools.asc)

2020-06-04 22:31 UTC, taichunmin requested changes

2020-06-04 22:31 UTC, taichunmin commented on ch07-git-tools.asc
> +到目前為止，你已經學到大部分常用的指令和管理、維護一個 Git 版本庫（repository）的流程來進行原始碼的操作，
翻譯不太通順

2020-06-04 22:31 UTC, taichunmin commented on ch07-git-tools.asc
> +現在你將學習 Git 強大的功能，這些或許不是天天使用的必要基本，但在一些情況下可能用得到。
一樣是翻譯不太通順

2020-06-04 22:31 UTC, taichunmin commented on ch07-git-tools.asc
> +如果你想要在專案裡使用子專案，你也了解怎麼達成這些需求。
「了解」->「學到」

2020-06-04 22:31 UTC, taichunmin commented on ch07-git-tools.asc
> +當你發現問題，你應該能夠輕易地知道涉及哪些提交（commit）、什麼時候和是誰造成的，
「知道涉及哪些提交（commit）、什麼時候和是誰造成的」->「知道是哪些提交（commit）、什麼時間和是誰造成的」

2020-06-05 14:20 UTC, chenuin commented on ch07-git-tools.asc
> +到目前為止，你已經學到大部分常用的指令和管理、維護一個 Git 版本庫（repository）的流程來進行原始碼的操作，
已修正

2020-06-05 14:20 UTC, chenuin commented on ch07-git-tools.asc
> +現在你將學習 Git 強大的功能，這些或許不是天天使用的必要基本，但在一些情況下可能用得到。
已修正

2020-06-05 14:20 UTC, chenuin commented on ch07-git-tools.asc
> +如果你想要在專案裡使用子專案，你也了解怎麼達成這些需求。
已修正

2020-06-28 22:08 UTC, taichunmin commented on ch07-git-tools.asc
> +這樣看來，你應該能夠輕鬆地在命令行完成 Git 大部分的常用操作。
「這樣看來」改成「到目前為止」會不會比較好呢？

2020-06-28 22:08 UTC, taichunmin commented on ch07-git-tools.asc
> +到目前為至，你已經學到管理或維護存放原始碼的 Git 版本庫（repository）大部分所需的常用指令和流程，
如果翻譯成「你已經學到用來管理或維護你原始碼的 Git 版本庫所需的大部分常用指令和流程，」

2020-07-01 13:04 UTC, chenuin commented on ch07-git-tools.asc
> +這樣看來，你應該能夠輕鬆地在命令行完成 Git 大部分的常用操作。
考慮到本章節第一句也是「到目前為止」，且略缺乏總結的感覺。不確定這樣會不會距離原文意思太遠，改成「現在你應該能夠輕鬆地在命令行完成 Git 大部分的常用操作」，另一個想法是「接下來你應該能夠輕鬆地在命令行完成 Git 大部分的常用操作」。

2020-07-01 13:11 UTC, chenuin commented on ch07-git-tools.asc
> +現在將為你探索一些 Git 的強大功能，這些功能你或許不一定會天天使用，但有時可能會派上用場。
已修正

2020-07-01 13:11 UTC, chenuin commented on ch07-git-tools.asc
> +到目前為至，你已經學到管理或維護存放原始碼的 Git 版本庫（repository）大部分所需的常用指令和流程，
已修正

2020-07-02 05:42 UTC, taichunmin approved these changes
已經看過囉，接下來麻煩你全部 squash 成一個 commit 吧！等你 squash 以後我就幫你按合併囉！

2020-07-03 05:49 UTC, chenuin commented
> 已經看過囉，接下來麻煩你全部 squash 成一個 commit 吧！等你 squash 以後我就幫你按合併囉！

已經更新分支，謝謝

2020-07-03 08:16 UTC, merged

2020-07-03 08:17 UTC, taichunmin commented
感謝協助翻譯